---
cloud_controller_uri: api.vcap.me
service:
  name: cassandra
  version: "1.6.1"
  description: 'Cassandra DB Service'
  plans: ['free']
  default_plan: free
  tags: ['Cassandra', 'Cassandra-1.6.1', 'cloudcredo']
ip_route: localhost
index: 0
token: cassandra-token
logging:
  level: debug
mbus: nats://localhost:4222/
pid: /var/vcap/sys/run/cassandra_service.pid
node_timeout: 2
