---
plan: free
capacity: 100
local_db: sqlite3:/tmp/cassandra_node.db
mbus: nats://localhost:4222
base_dir: /tmp/vcap/cassandra
index: 0
logging:
  level: debug
pid: testres/tmp/cassandra_node.pid
node_id: cassandra_node_1

default_version: "1.1.6"
supported_versions: ["1.1.6"]

host: "localhost"
#The absolute path of Cassandra
runtime_path: "cassandra"
#The maximum number of Cassandra instances allowed per host
instance_limit: 10

port_range:
  first: 5000
  last: 5020

ssl_port_range:
  first: 5021
  last:  5030

jmx_port_range:
  first: 5031
  last: 5040

rpc_port_range:
  first: 5041
  last: 5050

migration_nfs: /mnt/migration
service_start_timeout: 10

