---
# cloud_controller_uri: api.vcap.me
service:
  name: cassandra
  version: "1.6.1"
  timeout: 25
  description: 'Cassandra NoSQL store'
  plans: ['free']
  default_plan: free
  tags: ['Cassandra', 'Cassandra-1.6.1', 'cloudcredo']
  supported_versions: ["1.6.1"]
  version_aliases:
    "current": "1.6.1"

ip_route: 192.168.18.10
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: "cassandratoken"
mbus: nats://nats:nats@192.168.18.10:4222
logging:
  level: debug
pid: /var/vcap/sys/run/cassandra_service.pid
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
resque:
  host: localhost
  port: 5454
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}

plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      lifecycle:
        snapshots:
          quota: 5
        serialization: enable
        job: enable
      #allow_over_provisioning: false
